import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import Navbar from "./Components/Navbar";
import { ContextProvider } from "./appContext";
import "./globals.css";
import QueryProvider from "./QueryProvider";
import { QueryClient } from "@tanstack/react-query";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <ContextProvider>
            <Suspense fallback={null}>
              <Navbar />
            </Suspense>

            {children}
            <ToastContainer
              position="top-right"
              limit={4}
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop
              closeOnClick
              pauseOnHover
              theme="light"
            />
          </ContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
